# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fetch_mails.ui'
#
# Created: Fri Jun 17 16:32:45 2016
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form_fetch_mails(object):
    def setupUi(self, Form_fetch_mails):
        Form_fetch_mails.setObjectName("Form_fetch_mails")
        Form_fetch_mails.resize(612, 396)
        self.widget = QtGui.QWidget(Form_fetch_mails)
        self.widget.setGeometry(QtCore.QRect(10, 10, 591, 381))
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtGui.QGridLayout(self.widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_4 = QtGui.QFrame(self.widget)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(355, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(21, 21))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/ide_pic_Close.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.frame_8 = QtGui.QFrame(self.frame_4)
        self.frame_8.setStyleSheet("background-color:#ADD8E6")
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_7.addWidget(self.frame_8, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.widget)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_mail_fetch = QtGui.QLabel(self.frame_5)
        self.label_mail_fetch.setObjectName("label_mail_fetch")
        self.gridLayout_6.addWidget(self.label_mail_fetch, 0, 0, 1, 1)
        self.lineEdit_mail_label = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_mail_label.setObjectName("lineEdit_mail_label")
        self.gridLayout_6.addWidget(self.lineEdit_mail_label, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.widget)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_email = QtGui.QLabel(self.frame_6)
        self.label_email.setObjectName("label_email")
        self.gridLayout_5.addWidget(self.label_email, 0, 0, 1, 1)
        self.lineEdit_email = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout_5.addWidget(self.lineEdit_email, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.widget)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_password = QtGui.QLabel(self.frame_7)
        self.label_password.setObjectName("label_password")
        self.gridLayout_4.addWidget(self.label_password, 0, 0, 1, 1)
        self.lineEdit_password = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout_4.addWidget(self.lineEdit_password, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_7, 3, 0, 1, 1)
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_location = QtGui.QLabel(self.frame)
        self.label_location.setMaximumSize(QtCore.QSize(59, 17))
        self.label_location.setObjectName("label_location")
        self.gridLayout.addWidget(self.label_location, 0, 0, 1, 1)
        self.lineEdit_location = QtGui.QLineEdit(self.frame)
        self.lineEdit_location.setMaximumSize(QtCore.QSize(247, 27))
        self.lineEdit_location.setObjectName("lineEdit_location")
        self.gridLayout.addWidget(self.lineEdit_location, 0, 1, 1, 1)
        self.pushButton_select_location = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_location.sizePolicy().hasHeightForWidth())
        self.pushButton_select_location.setSizePolicy(sizePolicy)
        self.pushButton_select_location.setMaximumSize(QtCore.QSize(41, 27))
        self.pushButton_select_location.setObjectName("pushButton_select_location")
        self.gridLayout.addWidget(self.pushButton_select_location, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(248, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.frame, 4, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.widget)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_date = QtGui.QLabel(self.frame_2)
        self.label_date.setMaximumSize(QtCore.QSize(59, 17))
        self.label_date.setObjectName("label_date")
        self.gridLayout_2.addWidget(self.label_date, 0, 0, 1, 1)
        self.lineEdit_date = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_date.setMaximumSize(QtCore.QSize(247, 27))
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout_2.addWidget(self.lineEdit_date, 0, 1, 1, 1)
        self.pushButton_select_date = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_date.sizePolicy().hasHeightForWidth())
        self.pushButton_select_date.setSizePolicy(sizePolicy)
        self.pushButton_select_date.setMaximumSize(QtCore.QSize(41, 27))
        self.pushButton_select_date.setObjectName("pushButton_select_date")
        self.gridLayout_2.addWidget(self.pushButton_select_date, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.frame_2, 5, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.widget)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushButton_fetch_mails = QtGui.QPushButton(self.frame_3)
        self.pushButton_fetch_mails.setObjectName("pushButton_fetch_mails")
        self.gridLayout_3.addWidget(self.pushButton_fetch_mails, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.frame_3, 6, 0, 1, 1)

        self.retranslateUi(Form_fetch_mails)
        QtCore.QMetaObject.connectSlotsByName(Form_fetch_mails)

    def retranslateUi(self, Form_fetch_mails):
        Form_fetch_mails.setWindowTitle(QtGui.QApplication.translate("Form_fetch_mails", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form_fetch_mails", "Fetch Mails in text format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mail_fetch.setText(QtGui.QApplication.translate("Form_fetch_mails", "mail label having emails you want to fetch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_email.setText(QtGui.QApplication.translate("Form_fetch_mails", "E-Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password.setText(QtGui.QApplication.translate("Form_fetch_mails", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_location.setText(QtGui.QApplication.translate("Form_fetch_mails", "Location ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_select_location.setText(QtGui.QApplication.translate("Form_fetch_mails", "------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date.setText(QtGui.QApplication.translate("Form_fetch_mails", "Date ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_select_date.setText(QtGui.QApplication.translate("Form_fetch_mails", "------", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fetch_mails.setText(QtGui.QApplication.translate("Form_fetch_mails", "Fetch Mails", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form_fetch_mails = QtGui.QWidget()
    ui = Ui_Form_fetch_mails()
    ui.setupUi(Form_fetch_mails)
    Form_fetch_mails.show()
    sys.exit(app.exec_())

